title: COMPUTATIONAL MATHEMATICS AND COMPUTER ARCHITECTURE
description: question paper
template:
  repo: computational-mathematics-and-computer-architecture-template
  name: computational-mathematics-and-computer-architecture
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
